feature(elo-match-tracker): implemented CRUD for Players/Matches
chudnovskyi/elo-match-tracker pull request #1
Opened 2024-10-06 17:35 UTC by efremnikolaus

…ayers

2024-10-06 18:58 UTC, chudnovskyi commented on src/main/java/com/template/entity/Player.java
> +@Table(name = "player_",
we dont need an underscore here
It was used in the `user_` entity to avoid PostgreSQL reserved word

2024-10-06 19:01 UTC, chudnovskyi commented on src/main/java/com/template/entity/Player.java
> +  @Override
Dont need this since `@Data`

2024-10-06 19:01 UTC, chudnovskyi commented on src/main/java/com/template/entity/Player.java
> +  @Override
Dont need this since `@Data`

2024-10-06 19:02 UTC, chudnovskyi commented on src/main/resources/db/migration/V01__create_player_table.sql
> +CREATE TABLE player_
remove `_`

2024-10-06 19:03 UTC, chudnovskyi commented on src/main/resources/db/migration/V02__init_views.sql
> +FROM player_;
remove `_`

2024-10-06 19:04 UTC, chudnovskyi commented on src/main/resources/templates/login.html
We don't need authentication in this service, remove it

2024-10-06 19:04 UTC, chudnovskyi commented on src/main/resources/templates/register.html
We don't need authentication in this service, remove it

2024-10-06 19:09 UTC, chudnovskyi requested changes
Overall everything is very clear, todo:
1) Fix small changes, look at comments
2) Add an MVC endpoint that will `register` new players (basically just to create entity, no need to have authentication or any security), populate request parameters from HTML + thymeleaf page, display error message in case of any (e.g. username already exists)

2024-10-07 09:12 UTC, efremnikolaus commented on src/main/java/com/template/entity/Player.java
> +@Table(name = "player_",
done

2024-10-07 09:14 UTC, efremnikolaus commented on src/main/java/com/template/entity/Player.java
> +  @Override
done

2024-10-07 09:14 UTC, efremnikolaus commented on src/main/java/com/template/entity/Player.java
> +  @Override
done

2024-10-07 09:14 UTC, mykola-yefremov commented on src/main/resources/db/migration/V01__create_player_table.sql
> +CREATE TABLE player_
done

2024-10-07 09:15 UTC, efremnikolaus commented on src/main/resources/db/migration/V02__init_views.sql
> +FROM player_;
done

2024-10-07 10:16 UTC, chudnovskyi approved these changes

2024-10-07 19:19 UTC, efremnikolaus commented
ready for new reviewing

2024-10-08 19:17 UTC, chudnovskyi commented on src/main/java/com/template/service/PlayerService.java
> +            .collect(Collectors.toList());
personal preference: 
`.toList();`

2024-10-08 19:22 UTC, chudnovskyi commented on src/main/java/com/template/controller/PlayerController.java
> +    model.addAttribute("players", playerService.getAllPlayers());
Never expose entity itself, use playerResponse

2024-10-08 19:22 UTC, chudnovskyi commented on src/main/java/com/template/controller/PlayerController.java
> +    model.addAttribute("matches", matchService.getAllMatches());
Never expose entity itself, use matchResponse

2024-10-08 19:28 UTC, chudnovskyi commented on src/main/java/com/template/mapper/PlayerMapper.java
> +    return Player.builder().username(request.username()).eloRating(1000).build();
There's already exists default value `1000` for this field in the CREATE TABLE statement, remove this logic from java code

2024-10-08 19:28 UTC, chudnovskyi commented on src/main/java/com/template/entity/Player.java
> +  private Integer eloRating = 1000;
There's already exists default value `1000` for this field in the CREATE TABLE statement, remove this logic from java code

2024-10-08 20:12 UTC, chudnovskyi requested changes
Minor changes, look at the comments. Also:
1) Create proper IT with at least 80% coverage
2) Fix the app, Make it bootable!
3) Rename package root from `template` to `emt` or whatever
4) !!! Don't add any new features that are not mentioned in this mr !!!

2024-10-08 20:12 UTC, chudnovskyi commented on src/main/java/com/template/service/PlayerService.java
> +        .orElseThrow(() -> new PlayerAlreadyExistsException("Failed."));
This exception will never occure since there's a UNIQUE constraint on username field.
If you want to have an exception handling here, you can use `EXISTS (subquery)` operator, and throw if true for username
Also, you should provide request username into PlayerAlreadyExistsException constructor

2024-10-08 20:12 UTC, chudnovskyi commented on src/main/java/com/template/service/MatchService.java
If you use `google-java-format`, be consistent
Use `ctrl + alt + l` for auto-formatting

2024-10-08 20:12 UTC, chudnovskyi commented on src/main/java/com/template/model/exception/PlayerAlreadyExistsException.java
> +        super("Player with username '" + username + "' already exists.");
[nit]: use .formatted()

2024-10-08 20:12 UTC, chudnovskyi commented on src/main/java/com/template/service/MatchService.java
> +                .collect(Collectors.toList());
.toList()

2024-10-08 20:12 UTC, chudnovskyi commented on src/main/java/com/template/model/request/MatchRequest.java
> +        int player1Score,
We don't need to trace exact player's score in matches, remove for both players

2024-10-08 20:12 UTC, chudnovskyi commented on src/main/java/com/template/service/MatchService.java
> +                .orElseThrow(() -> new MatchAlreadyExistsException("Failed to create match."));
This exception is not connected with a logic flow;
I'd say, it can be smth like an `UnexpectedException`, because we don't know the cause of null result here. Or even `UnreachableException`;

I would prefere not using optional map chaining here, not the best place

2024-10-08 20:12 UTC, chudnovskyi commented on src/main/java/com/template/model/exception/MatchAlreadyExistsException.java
remove this class, it has no purpose

2024-10-08 20:12 UTC, chudnovskyi commented on src/main/java/com/template/mapper/MatchMapper.java
> +    private final PlayerRepository playerRepository;
Best practice is not to have any non/business logic in mappers, remove repository, handle entity retrieval/mapping outside

2024-10-08 20:12 UTC, chudnovskyi commented on src/main/java/com/template/mapper/MatchMapper.java
> +        String outcome = (match.getPlayer1Score() > match.getPlayer2Score())
Remove logic from mapper class.
We will not use player`s score here, remove this logic at all. You can simply get the winner from request model

2024-10-08 20:12 UTC, chudnovskyi commented on src/main/java/com/template/mapper/MatchMapper.java
> +        return new MatchResponse(
[nit]: consider @Builder

2024-10-08 20:12 UTC, chudnovskyi commented on src/main/java/com/template/mapper/MatchMapper.java
> +        Player player1 = playerRepository.findById(request.player1Id())
handle logic outside of mapper class

2024-10-08 20:12 UTC, chudnovskyi commented on src/main/java/com/template/mapper/MatchMapper.java
> +                .orElseThrow(() -> new IllegalArgumentException("Invalid Player 1 ID"));
use custom exception handler: `PlayerNotFoundException(id)`

2024-10-08 20:12 UTC, chudnovskyi commented on src/main/java/com/template/entity/Match.java
> +@Table(name = "match")
first of all, if you created a dedicated view for match table, use view!
in this case, we will decommission all views from migration script, since it's a monolithic app

2024-10-08 20:12 UTC, chudnovskyi commented on src/main/java/com/template/entity/Match.java
> +    private int player2Score;
decommission

2024-10-08 20:12 UTC, chudnovskyi commented on src/main/java/com/template/entity/Match.java
> +    private LocalDateTime matchDate = LocalDateTime.now();
preferred to use Instant to keep tz, also remove default values since it's already there in the db

2024-10-08 20:12 UTC, chudnovskyi commented on src/main/java/com/template/entity/Match.java
> +    @Column(name = "match_date", updatable = false)
name is ambiguous here, could be removed

2024-10-08 20:12 UTC, chudnovskyi commented on src/main/java/com/template/entity/Match.java
> +    private Player player1;
winner

2024-10-08 20:12 UTC, chudnovskyi commented on src/main/java/com/template/entity/Match.java
> +    private Player player2;
looser

2024-10-08 20:12 UTC, chudnovskyi commented on src/main/java/com/template/model/request/PlayerRequest.java
> +public record PlayerRequest(@NotEmpty String username) { }
rename to `CreatePlayerRequest`

2024-10-08 20:12 UTC, chudnovskyi commented on src/main/java/com/template/model/response/MatchResponse.java
fix according to other comments

2024-10-08 20:12 UTC, chudnovskyi commented on src/main/resources/db/migration/V01__init_tables.sql
Important: Never change existing migration scripts `after` code reviews, and don't add additional logic that's not part of initial mr

2024-10-08 20:12 UTC, chudnovskyi commented on src/main/resources/db/migration/V01__init_tables.sql
> +    username VARCHAR(100) UNIQUE NOT NULL,
text type is preferable:
[source](https://stackoverflow.com/questions/4848964/difference-between-text-and-varchar-character-varying)

2024-10-08 20:12 UTC, chudnovskyi commented on src/main/resources/db/migration/V01__init_tables.sql
> +    registered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
TIMESTAMPTZ

2024-10-08 20:12 UTC, chudnovskyi commented on src/main/resources/db/migration/V01__init_tables.sql
> +);
refactor according to Match entity changes

2024-10-08 20:12 UTC, chudnovskyi commented on src/main/resources/db/migration/V02__init_views.sql
decommission views

2024-10-08 20:12 UTC, chudnovskyi commented on src/main/resources/templates/elo-ranking.html
Make sure it works:
start docker container and app locally, test all the logic

2024-10-08 20:12 UTC, chudnovskyi commented on src/main/resources/templates/match-history.html
Make sure it works:
start docker container and app locally, test all the logic

2024-10-08 20:12 UTC, chudnovskyi commented on src/test/integration/java/com/template/controller/PlayerControllerIT.java
make it work, 80% coverage at least

2024-10-12 18:42 UTC, efremnikolaus commented
- Note: Tests not implemented yet.

2024-10-12 23:29 UTC, chudnovskyi commented on src/main/java/com/emt/controller/MatchController.java
> +      @RequestParam Long loserId,
You don't need these request parameters, there's a `winnerId` present in `CreateMatchRequest`

2024-10-12 23:31 UTC, chudnovskyi commented on src/main/java/com/emt/controller/MatchController.java
> +      redirectAttributes.addFlashAttribute("error", "An error occurred while reporting the match.");
Use dedicated ExceptionHandling and display exception message in UI in case of any

2024-10-12 23:34 UTC, chudnovskyi commented on src/main/java/com/emt/mapper/MatchMapper.java
> +  public Match mapToEntity(CreateMatchRequest request, Player winner, Player loser) {
`request` param is not used, remove

2024-10-12 23:40 UTC, chudnovskyi commented on src/main/java/com/emt/controller/PlayerController.java
> +      redirectAttributes.addFlashAttribute("error", e.getMessage());
leverage exception handling here

2024-10-12 23:41 UTC, chudnovskyi commented on src/main/java/com/emt/entity/Match.java
> +  private Instant matchDate;
better use `matchTime` to indicate that it's a specific point in time

2024-10-12 23:41 UTC, chudnovskyi commented on src/main/java/com/emt/entity/Match.java
> +  private MatchOutcome outcome;
We don't need it here, remove

2024-10-12 23:42 UTC, chudnovskyi commented on src/main/java/com/emt/entity/Player.java
>    private String username;
[nit]: rename to nickname

2024-10-12 23:50 UTC, chudnovskyi commented on src/main/java/com/emt/repository/PlayerRepository.java
> +      "SELECT CASE WHEN COUNT(p) > 0 THEN true ELSE false END FROM Player p WHERE p.username = ?1")
[nit]: You can use Spring JPA's query derivation for generating simple queries like this one

2024-10-12 23:51 UTC, chudnovskyi commented on src/main/java/com/emt/service/MatchService.java
> +              match.setOutcome(MatchOutcome.VICTORY);
Doesn't make sende, remoe please

2024-10-12 23:52 UTC, chudnovskyi commented on src/main/java/com/emt/service/PlayerService.java
> +              player.setRegisteredAt(Instant.now());
you can set `Instant.now()` in mapToEntity method, it's not considered as business logic and will simplyfy chaining:
`playerRepository::save`

2024-10-12 23:54 UTC, chudnovskyi requested changes
Minor code adjustments needed

2024-10-17 11:06 UTC, chudnovskyi approved these changes
TODO: fix html

2024-10-17 11:06 UTC, merged